[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "." # Root directory for static files

[functions]
  included_files = ["main.py", "src/**/*.py", "requirements.txt"]
  directory = "netlify/functions"
  python_version = "3.12"